version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: app
    build:
      context: .
      dockerfile: DockerfileFront
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "80:80"
  express:
    container_name: express
    build:
      context: ./
      dockerfile: DockerfileBack
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - SERVICE_URL=mongodb:27017
