services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    build: ""
    ports:
      - "27017:27017"
  app:
    container_name: app
    build:
      context: .
      dockerfile: DockerfileFront
    volumes:
      - ./:/app
    ports:
      - "80:80"
  express:
    container_name: express
    build:
      context: .
      dockerfile: DockerfileBack
    ports:
      - "3000:3000"
